<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.Infrastructure</RootNamespace>
    <AssemblyName>Samba.Infrastructure</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="6.0.0" />
    <PackageReference Include="System.Runtime.Serialization" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="ExceptionReporter\*.cs" />
    <Compile Include="Cron\*.cs" />
    <Compile Include="Helpers\*.cs" />
    <Compile Include="Messaging\*.cs" />
    <Compile Include="Settings\LocalSettings.cs" />
    <Compile Include="IMessageListener.cs" />
    <Compile Include="IStringCompareable.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)\SambaSetup\src"

:End</PostBuildEvent>
  </PropertyGroup>

  <PropertyGroup>
    <PreBuildEvent>net stop SambaPOS3-MessagingServer
Exit /b 0</PreBuildEvent>
  </PropertyGroup>
</Project>