<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.Infrastructure.Data</RootNamespace>
    <AssemblyName>Samba.Infrastructure.Data</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Omu.ValueInjecter" Version="3.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="BinarySerializer\*.cs" />
    <Compile Include="Injection\*.cs" />
    <Compile Include="Serializer\*.cs" />
    <Compile Include="SQL\*.cs" />
    <Compile Include="Text\*.cs" />
    <Compile Include="Validation\*.cs" />
    <Compile Include="IEntityClass.cs" />
    <Compile Include="IValueClass.cs" />
    <Compile Include="IAbstractMapModel.cs" />
    <Compile Include="ICacheable.cs" />
    <Compile Include="IEntityCreator.cs" />
    <Compile Include="IOrderable.cs" />
    <Compile Include="IReadOnlyWorkspace.cs" />
    <Compile Include="IWorkspace.cs" />
    <Compile Include="CollectionIdUpdater.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samba.Infrastructure\Samba.Infrastructure.csproj" />
    <ProjectReference Include="..\Samba.Localization\Samba.Localization.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)SambaSetup\src"
copy "$(SolutionDir)Lib\EntityFramework.dll" "$(SolutionDir)SambaSetup\src"

:End</PostBuildEvent>
  </PropertyGroup>
</Project>