<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.Modules.CidMonitor</RootNamespace>
    <AssemblyName>Samba.Modules.CidMonitor</AssemblyName>
    <OutputType>Library</OutputType>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AxInterop.cidv5callerid">
      <HintPath>../Lib/AxInterop.cidv5callerid.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>