<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.Modules.DepartmentModule</RootNamespace>
    <AssemblyName>Samba.Modules.DepartmentModule</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.0.0" />
    <PackageReference Include="Prism.Core" Version="8.0.0" />
  </ItemGroup>

</Project>