<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.Presentation.Services</RootNamespace>
    <AssemblyName>Samba.Presentation.Services</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="8.0.0" />
  </ItemGroup>

</Project>