<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.Presentation.Controls</RootNamespace>
    <AssemblyName>Samba.Presentation.Controls</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GongSolutions.Wpf.DragDrop" Version="2.3.0" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="PropertyTools" Version="2022.1.0" />
    <PackageReference Include="PropertyTools.Wpf" Version="2022.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="**/*.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images/*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Browser/Images/*.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samba.Domain\Samba.Domain.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure.Data\Samba.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure\Samba.Infrastructure.csproj" />
    <ProjectReference Include="..\Samba.Localization\Samba.Localization.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Common\Samba.Presentation.Common.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Services\Samba.Presentation.Services.csproj" />
    <ProjectReference Include="..\Samba.Services\Samba.Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)SambaSetup\src"

:End</PostBuildEvent>
  </PropertyGroup>
</Project>