<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>Samba.MessagingServer.WindowsService</RootNamespace>
    <AssemblyName>Samba.MessagingServer.WindowsService</AssemblyName>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
    <EmbeddedResource Include="**/*.resx" />
    <None Include="App.config" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samba.Infrastructure\Samba.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)SambaSetup\src"

:End</PostBuildEvent>
    <PreBuildEvent>net stop SambaPOS3-MessagingServer
Exit /b 0</PreBuildEvent>
  </PropertyGroup>
</Project>