<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.Persistance</RootNamespace>
    <AssemblyName>Samba.Persistance</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="3.3.0" />
    <PackageReference Include="Omu.ValueInjecter" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Samba.Domain/Samba.Domain.csproj" />
    <ProjectReference Include="../Samba.Infrastructure.Data/Samba.Infrastructure.Data.csproj" />
    <ProjectReference Include="../Samba.Infrastructure/Samba.Infrastructure.csproj" />
    <ProjectReference Include="../Samba.Localization/Samba.Localization.csproj" />
  </ItemGroup>

</Project>