<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.Persistance.DBMigration</RootNamespace>
    <AssemblyName>Samba.Persistance.DBMigration</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="3.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samba.Domain\Samba.Domain.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure.Data\Samba.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure\Samba.Infrastructure.csproj" />
    <ProjectReference Include="..\Samba.Localization\Samba.Localization.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Services\Samba.Presentation.Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)SambaSetup\src"

:End</PostBuildEvent>
  </PropertyGroup>
</Project>