<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.Presentation.ViewModels</RootNamespace>
    <AssemblyName>Samba.Presentation.ViewModels</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.0.0" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="CommonServiceLocator" Version="2.0.6" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samba.Domain\Samba.Domain.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure.Data\Samba.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure\Samba.Infrastructure.csproj" />
    <ProjectReference Include="..\Samba.Localization\Samba.Localization.csproj" />
    <ProjectReference Include="..\Samba.Persistance\Samba.Persistance.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Common\Samba.Presentation.Common.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Controls\Samba.Presentation.Controls.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Services\Samba.Presentation.Services.csproj" />
    <ProjectReference Include="..\Samba.Services\Samba.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="MapControllerView.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)SambaSetup\src"

:End</PostBuildEvent>
  </PropertyGroup>
</Project>