<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Samba.MessagingServer</RootNamespace>
    <AssemblyName>Samba.MessagingServer</AssemblyName>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
    <EmbeddedResource Include="**/*.resx" />
    <None Include="app.config" />
    <None Include="Properties/Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samba.Infrastructure\Samba.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)SambaSetup\src"
xcopy /y "$(TargetDir)tr\Samba.MessagingServer.resources.dll" "$(SolutionDir)SambaSetup\src\tr\"

:End</PostBuildEvent>
  </PropertyGroup>
</Project>
