<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Samba.Modules.ManagementModule</RootNamespace>
    <AssemblyName>Samba.Modules.ManagementModule</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Mef" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
    <Page Include="**/*.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samba.Localization\Samba.Localization.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Common\Samba.Presentation.Common.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Controls\Samba.Presentation.Controls.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Services\Samba.Presentation.Services.csproj" />
    <ProjectReference Include="..\Samba.Services\Samba.Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)SambaSetup\src"

:End</PostBuildEvent>
  </PropertyGroup>
</Project>