<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Samba.Presentation</RootNamespace>
    <AssemblyName>Samba.Presentation</AssemblyName>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GongSolutions.Wpf.DragDrop" Version="2.3.0" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Mef" Version="8.1.97" />
    <PackageReference Include="CommonServiceLocator" Version="2.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
    <Compile Include="**/*.cs" />
    <Page Include="**/*.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images/*.png" />
    <Resource Include="apple.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Imports/*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="migrate.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samba.Localization\Samba.Localization.csproj" />
    <ProjectReference Include="..\Samba.Modules.AccountModule\Samba.Modules.AccountModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.AutomationModule\Samba.Modules.AutomationModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.CidMonitor\Samba.Modules.CidMonitor.csproj" />
    <ProjectReference Include="..\Samba.Modules.DepartmentModule\Samba.Modules.DepartmentModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.EntityModule\Samba.Modules.EntityModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.InventoryModule\Samba.Modules.InventoryModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.LoginModule\Samba.Modules.LoginModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.ManagementModule\Samba.Modules.ManagementModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.MarketModule\Samba.Modules.MarketModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.ModifierModule\Samba.Modules.ModifierModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.NavigationModule\Samba.Modules.NavigationModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.PaymentModule\Samba.Modules.PaymentModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.PosModule\Samba.Modules.PosModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.PrinterModule\Samba.Modules.PrinterModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.TaskModule\Samba.Modules.TaskModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.UserModule\Samba.Modules.UserModule.csproj" />
    <ProjectReference Include="..\Samba.Domain\Samba.Domain.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure.Data\Samba.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure\Samba.Infrastructure.csproj" />
    <ProjectReference Include="..\Samba.Modules.MenuModule\Samba.Modules.MenuModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.SettingsModule\Samba.Modules.SettingsModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.TicketModule\Samba.Modules.TicketModule.csproj" />
    <ProjectReference Include="..\Samba.Modules.WorkperiodModule\Samba.Modules.WorkperiodModule.csproj" />
    <ProjectReference Include="..\Samba.Persistance.DBMigration\Samba.Persistance.DBMigration.csproj" />
    <ProjectReference Include="..\Samba.Persistance\Samba.Persistance.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Common\Samba.Presentation.Common.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Controls\Samba.Presentation.Controls.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Services\Samba.Presentation.Services.csproj" />
    <ProjectReference Include="..\Samba.Presentation.ViewModels\Samba.Presentation.ViewModels.csproj" />
    <ProjectReference Include="..\Samba.Services\Samba.Services.csproj" />
    <ProjectReference Include="..\Samba.Modules.BasicReports\Samba.Modules.BasicReports.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)$(TargetFileName).manifest" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)$(TargetFileName).config" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)Microsoft.Practices.Prism.Interactivity.dll" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)Microsoft.Practices.Prism.MefExtensions.dll" "$(SolutionDir)SambaSetup\src"

:End</PostBuildEvent>
  </PropertyGroup>
</Project>