<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Samba.ApiServer</RootNamespace>
    <AssemblyName>Samba.ApiServer</AssemblyName>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.9" />
    <PackageReference Include="Microsoft.AspNet.WebApi.SelfHost" Version="5.2.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
    <EmbeddedResource Include="**/*.resx" />
    <None Include="packages.config" />
    <None Include="Properties/Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samba.Domain\Samba.Domain.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure.Data\Samba.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\Samba.Infrastructure\Samba.Infrastructure.csproj" />
    <ProjectReference Include="..\Samba.Persistance\Samba.Persistance.csproj" />
    <ProjectReference Include="..\Samba.Presentation.Services\Samba.Presentation.Services.csproj" />
    <ProjectReference Include="..\Samba.Services\Samba.Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>IF NOT "$(ConfigurationName)"=="Release" GOTO End

copy "$(TargetDir)$(TargetFileName)" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)Newtonsoft.Json.dll" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)System.Net.Http.dll" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)System.Net.Http.Formatting.dll" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)System.Net.Http.WebRequest.dll" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)System.Web.Http.dll" "$(SolutionDir)SambaSetup\src"
copy "$(TargetDir)System.Web.Http.SelfHost.dll" "$(SolutionDir)SambaSetup\src"

:End</PostBuildEvent>
  </PropertyGroup>
</Project>